apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-fshare
  labels:
    app: vuln-fshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-fshare
  template:
    metadata:
      labels:
        app: vuln-fshare
    spec:
      containers:
      - name: vuln-fshare
        image: prex55/vuln_fshare:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vuln-fshare
spec:
  selector:
    app: vuln-fshare
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080  # ClusterIP Port
    targetPort: 80 # 
    nodePort: 30080 # NodePort Port range 30000-32767
